Repository Capstone-FA25/booking-care-system-ui-admin, pull requests merged in 2025-09, with the labels that each got.

#4 Merge request from init/initial-codebase-admin_HieuMX into develop
  .github/workflows/deploy.yml
  .github/workflows/preview.yml
  .gitignore
  .prettierignore
  tsconfig.json
  tsconfig.tsbuildinfo
Labels: config

#7 Merge request from feature/ui-header-sidebar_HieuMX into develop
  package-lock.json
  package.json
  src/layouts/MainLayout/MainLayout.module.scss
  src/layouts/MainLayout/MainLayout.tsx
  src/layouts/components/MainFooter/MainFooter.tsx
  src/layouts/components/MainFooter/index.ts
  src/layouts/components/MainHeader/MainHeader.tsx
  src/layouts/components/Sidenav/Sidenav.tsx
  src/layouts/components/Sidenav/components/GroupMenuItem/GroupMenuItem.tsx
  src/layouts/components/Sidenav/components/GroupMenuItem/index.ts
  src/layouts/components/Sidenav/components/MenuItem/MenuItem.module.scss
  src/layouts/components/Sidenav/components/MenuItem/MenuItem.tsx
  src/layouts/components/Sidenav/components/MenuItem/index.ts
  src/layouts/components/Sidenav/index.ts
  src/layouts/components/Sidenav/sidenav.data.ts
  src/main.tsx
  src/pages/admins/Dashboard/Dashboard.module.scss
  src/pages/admins/Dashboard/Dashboard.tsx
  src/pages/admins/Dashboard/index.ts
  src/pages/errors/NotFoundError/NotFoundError.tsx
  src/pages/errors/NotFoundError/index.ts
  src/routes/paths.ts
  src/routes/routeConfig.tsx
Labels: feature

#9 Merge request from config/config-cicd-pipeline_HieuMX into develop
  .github/workflows/preview.yml
Labels: config

#11 Merge request from config/config-sonar_HieuMX into develop
  sonar-project.properties
Labels: config

#12 Merge request from hotfix/embeded-css_HieuMX into develop
  src/main.tsx
Labels: bug, hotfix

#14 Merge request from feature/list-doctor-TuDT into develop
  index.html
  package-lock.json
  src/components/Calendar/Calendar.tsx
  src/components/Calendar/components/DateCustomize.tsx
  src/components/Calendar/index.ts
  src/main.tsx
  src/pages/clinics/Doctors/ListDoctors/ListDoctors.module.scss
  src/pages/clinics/Doctors/ListDoctors/ListDoctors.tsx
Labels: feature
